services:
  local:
    image: python-backend-lecture-3-local:latest
    build:
      context: ../../..
      dockerfile: ./lecture_2/hw/docker/Dockerfile
    restart: always
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    volumes:
      - ../settings/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
